# ============================================================
# Metagenomics_1_1_review_ready.R
# Reproducible visualization of species-level LEfSe markers
#
# This script MUST be run after Metagenomics_1_0_review_ready.R.
# It reads the RDS analysis object generated by Script 1_0.


rm(list = ls())
options(stringsAsFactors = FALSE)

# ----------------------------
# 0. Parameters
# ----------------------------
OUTDIR <- "Results/Metagenomics_species"
RDS_FILE <- file.path(
  OUTDIR,
  "metagenomics_species_analysis_object.rds"
)

FIGDIR <- file.path(OUTDIR, "family_boxplots")
dir.create(FIGDIR, recursive = TRUE, showWarnings = FALSE)

# Families pre-specified for biological presentation.
# This is a figure-selection rule only; it does not define significance.
FOCUS_FAMILIES <- c(
  "Lachnospiraceae",
  "Bacteroidaceae",
  "Prevotellaceae",
  "Lactobacillaceae",
  "Bifidobacteriaceae",
  "Rikenellaceae",
  "Streptococcaceae"
)

MAX_SPECIES_PER_FAMILY <- 8L

# If TRUE, only LEfSe markers additionally supported by BH-FDR < 0.05
# are eligible for the figure. If FALSE, all standard LEfSe markers
# are eligible, but stars still reflect BH-FDR.
REQUIRE_FDR_SUPPORT_FOR_DISPLAY <- FALSE

# ----------------------------
# 1. Packages
# ----------------------------
required_pkgs <- c(
  "dplyr", "tidyr", "ggplot2", "scales"
)

missing_pkgs <- required_pkgs[
  !vapply(required_pkgs, requireNamespace, quietly = TRUE, FUN.VALUE = logical(1))
]

if (length(missing_pkgs) > 0) {
  stop(
    "Missing required packages: ",
    paste(missing_pkgs, collapse = ", ")
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(scales)
})

if (!file.exists(RDS_FILE)) {
  stop(
    "Required analysis object not found: ", RDS_FILE,
    "\nRun Metagenomics_1_0_review_ready.R first."
  )
}

obj <- readRDS(RDS_FILE)

required_obj <- c(
  "meta", "taxonomy", "relative_abundance",
  "all_feature_stats", "lefse_markers"
)

missing_obj <- setdiff(required_obj, names(obj))
if (length(missing_obj) > 0) {
  stop(
    "Analysis object is missing elements: ",
    paste(missing_obj, collapse = ", ")
  )
}

meta <- obj$meta
taxonomy <- obj$taxonomy
relative_abundance <- obj$relative_abundance
feature_stats <- obj$all_feature_stats
marker_df <- obj$lefse_markers

if (!identical(rownames(relative_abundance), meta$Subid)) {
  stop("Sample order mismatch in saved analysis object.")
}

# ----------------------------
# 2. Define eligible marker set programmatically
# ----------------------------
eligible_markers <- marker_df

if (REQUIRE_FDR_SUPPORT_FOR_DISPLAY) {
  eligible_markers <- eligible_markers %>%
    filter(FDR_supported)
}

eligible_markers <- eligible_markers %>%
  filter(Family %in% FOCUS_FAMILIES)

# Select at most the top N LEfSe markers per family using a deterministic
# algorithm. No manual species list is allowed to overwrite this result.
selected_markers <- eligible_markers %>%
  group_by(Family) %>%
  arrange(
    desc(LEfSe_LDA),
    Wilcoxon_FDR_BH,
    Species,
    FeatureID,
    .by_group = TRUE
  ) %>%
  slice_head(n = MAX_SPECIES_PER_FAMILY) %>%
  ungroup()

write.csv(
  selected_markers,
  file.path(OUTDIR, "selected_species_for_family_boxplots.csv"),
  row.names = FALSE
)

# Audit which requested families are absent.
family_selection_audit <- data.frame(
  Family = FOCUS_FAMILIES,
  N_EligibleMarkers = vapply(
    FOCUS_FAMILIES,
    function(fam) {
      sum(eligible_markers$Family == fam)
    },
    integer(1)
  ),
  N_SelectedForPlot = vapply(
    FOCUS_FAMILIES,
    function(fam) {
      sum(selected_markers$Family == fam)
    },
    integer(1)
  ),
  stringsAsFactors = FALSE
)

write.csv(
  family_selection_audit,
  file.path(OUTDIR, "family_boxplot_selection_audit.csv"),
  row.names = FALSE
)

if (nrow(selected_markers) == 0) {
  stop(
    "No eligible markers were available for the pre-specified focus families."
  )
}

# ----------------------------
# 3. Build long-format observed abundance data
# ----------------------------
selected_ids <- selected_markers$FeatureID

abundance_df <- data.frame(
  Subid = meta$Subid,
  group = as.character(meta$group),
  relative_abundance[
    ,
    selected_ids,
    drop = FALSE
  ],
  check.names = FALSE
)

long_df <- abundance_df %>%
  pivot_longer(
    cols = all_of(selected_ids),
    names_to = "FeatureID",
    values_to = "RelativeAbundance"
  ) %>%
  left_join(
    selected_markers %>%
      select(
        FeatureID, Species, Family, Phylum,
        LEfSe_EnrichedGroup, LEfSe_LDA,
        LEfSe_KW_P, Wilcoxon_P, Wilcoxon_FDR_BH,
        FDR_supported
      ),
    by = "FeatureID"
  )

if (anyNA(long_df$Family)) {
  stop("Some selected features failed to join to marker metadata.")
}

# ----------------------------
# 4. Create unique display labels without changing data
# ----------------------------
# Repeated generic species names can exist for distinct source features.
# The underlying FeatureID remains the analysis key.
label_lookup <- selected_markers %>%
  group_by(Family, Species) %>%
  mutate(
    DuplicateDisplayName = n() > 1,
    SpeciesLabel = ifelse(
      DuplicateDisplayName,
      paste0(Species, " [", FeatureID, "]"),
      Species
    )
  ) %>%
  ungroup() %>%
  select(FeatureID, SpeciesLabel)

long_df <- long_df %>%
  left_join(label_lookup, by = "FeatureID")

selected_markers <- selected_markers %>%
  left_join(label_lookup, by = "FeatureID")

# ----------------------------
# 5. Significance labels from true BH-FDR q-values
# ----------------------------
star_df <- selected_markers %>%
  mutate(
    Significance = case_when(
      is.na(Wilcoxon_FDR_BH) ~ "",
      Wilcoxon_FDR_BH < 0.001 ~ "***",
      Wilcoxon_FDR_BH < 0.01 ~ "**",
      Wilcoxon_FDR_BH < 0.05 ~ "*",
      TRUE ~ ""
    )
  )

# ----------------------------
# 6. Pseudo-log display scale for zero-containing relative abundance
# ----------------------------
positive_values <- long_df$RelativeAbundance[
  is.finite(long_df$RelativeAbundance) &
    long_df$RelativeAbundance > 0
]

if (length(positive_values) == 0) {
  stop("No positive relative-abundance values are available for plotting.")
}

# Data-adaptive transition around zero.
# This affects visualization only; it is NOT used for statistical tests.
PSEUDOLOG_SIGMA <- min(positive_values) / 2

plot_parameters <- data.frame(
  Parameter = c(
    "MAX_SPECIES_PER_FAMILY",
    "REQUIRE_FDR_SUPPORT_FOR_DISPLAY",
    "PSEUDOLOG_SIGMA",
    "SIGNIFICANCE_SOURCE"
  ),
  Value = c(
    MAX_SPECIES_PER_FAMILY,
    REQUIRE_FDR_SUPPORT_FOR_DISPLAY,
    format(PSEUDOLOG_SIGMA, scientific = TRUE),
    "Wilcoxon tests across all prevalence-filtered features; BH-FDR"
  ),
  stringsAsFactors = FALSE
)

write.csv(
  plot_parameters,
  file.path(OUTDIR, "family_boxplot_parameters.csv"),
  row.names = FALSE
)

# ----------------------------
# 7. Plot each family using only observed samples
# ----------------------------
group_colors <- c(
  "HCs" = "#457B9D",
  "PMI" = "#E76F51"
)

plot_manifest <- list()

for (fam in FOCUS_FAMILIES) {

  fam_markers <- selected_markers %>%
    filter(Family == fam)

  if (nrow(fam_markers) == 0) {
    next
  }

  # Preserve deterministic ranking within family.
  fam_order <- fam_markers %>%
    arrange(
      desc(LEfSe_LDA),
      Wilcoxon_FDR_BH,
      SpeciesLabel
    ) %>%
    pull(SpeciesLabel)

  df_sub <- long_df %>%
    filter(Family == fam) %>%
    mutate(
      SpeciesLabel = factor(
        SpeciesLabel,
        levels = fam_order
      ),
      group = factor(
        group,
        levels = c("HCs", "PMI")
      )
    )

  # Y positions for FDR stars are based only on observed values.
  star_fam <- star_df %>%
    filter(Family == fam) %>%
    left_join(label_lookup, by = "FeatureID") %>%
    left_join(
      df_sub %>%
        group_by(FeatureID) %>%
        summarise(
          Ymax = max(RelativeAbundance, na.rm = TRUE),
          .groups = "drop"
        ),
      by = "FeatureID"
    ) %>%
    mutate(
      SpeciesLabel = factor(
        SpeciesLabel,
        levels = fam_order
      ),
      Ystar = pmax(
        Ymax * 1.35,
        PSEUDOLOG_SIGMA * 2
      )
    )

  p_fam <- ggplot(
    df_sub,
    aes(
      x = SpeciesLabel,
      y = RelativeAbundance,
      fill = group
    )
  ) +
    geom_boxplot(
      position = position_dodge(width = 0.65),
      outlier.shape = NA,
      width = 0.52,
      linewidth = 0.55
    ) +
    geom_point(
      aes(color = group),
      position = position_jitterdodge(
        jitter.width = 0.10,
        dodge.width = 0.65
      ),
      size = 0.8,
      alpha = 0.55,
      show.legend = FALSE
    ) +
    geom_text(
      data = star_fam,
      aes(
        x = SpeciesLabel,
        y = Ystar,
        label = Significance
      ),
      inherit.aes = FALSE,
      vjust = 0,
      size = 3.6,
      color = "black"
    ) +
    scale_fill_manual(
      values = group_colors,
      breaks = c("HCs", "PMI")
    ) +
    scale_color_manual(
      values = group_colors,
      breaks = c("HCs", "PMI")
    ) +
    scale_y_continuous(
      trans = scales::pseudo_log_trans(
        base = 10,
        sigma = PSEUDOLOG_SIGMA
      ),
      labels = scales::label_scientific(digits = 2),
      expand = expansion(mult = c(0.05, 0.16))
    ) +
    labs(
      x = NULL,
      y = "Relative abundance",
      fill = "Group",
      title = fam,
      subtitle = paste0(
        "Top LEfSe markers (max ",
        MAX_SPECIES_PER_FAMILY,
        "); stars denote BH-FDR q values"
      ),
      caption = paste0(
        "* q<0.05; ** q<0.01; *** q<0.001. ",
        "BH correction was performed across all prevalence-filtered features."
      )
    ) +
    theme_bw(base_size = 11) +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        face = "italic",
        size = 9
      ),
      legend.position = "top",
      plot.title = element_text(
        face = "bold",
        hjust = 0.5
      ),
      plot.subtitle = element_text(
        hjust = 0.5,
        size = 9
      ),
      plot.caption = element_text(
        hjust = 0,
        size = 8
      )
    )

  outfile_pdf <- file.path(
    FIGDIR,
    paste0(
      gsub("[^A-Za-z0-9_-]", "_", fam),
      "_LEfSe_marker_species_boxplot.pdf"
    )
  )

  outfile_png <- sub(
    "\\.pdf$",
    ".png",
    outfile_pdf
  )

  fig_width <- max(
    5.5,
    0.78 * length(fam_order) + 2.0
  )

  ggsave(
    outfile_pdf,
    p_fam,
    width = fig_width,
    height = 5.4
  )

  ggsave(
    outfile_png,
    p_fam,
    width = fig_width,
    height = 5.4,
    dpi = 600
  )

  plot_manifest[[fam]] <- data.frame(
    Family = fam,
    N_SpeciesPlotted = length(fam_order),
    PDF = outfile_pdf,
    PNG = outfile_png,
    stringsAsFactors = FALSE
  )
}

plot_manifest <- bind_rows(plot_manifest)

write.csv(
  plot_manifest,
  file.path(OUTDIR, "family_boxplot_manifest.csv"),
  row.names = FALSE
)

# ----------------------------
# 8. Export long plotting data for full auditability
# ----------------------------
write.csv(
  long_df,
  file.path(OUTDIR, "family_boxplot_observed_data_long.csv"),
  row.names = FALSE
)

# ----------------------------
# 9. Console summary
# ----------------------------
cat("\n========================================\n")
cat("Family-level marker plots complete\n")
cat("========================================\n")
cat("Focus families requested:", length(FOCUS_FAMILIES), "\n")
cat(
  "Families with plotted markers:",
  length(unique(selected_markers$Family)),
  "\n"
)
cat("Selected marker features:", nrow(selected_markers), "\n")
cat("Maximum per family:", MAX_SPECIES_PER_FAMILY, "\n")
cat(
  "FDR support required for eligibility:",
  REQUIRE_FDR_SUPPORT_FOR_DISPLAY,
  "\n"
)
cat(
  "No species were duplicated or padded to standardize panel size.\n"
)
cat("Figures saved to:", FIGDIR, "\n")
cat("========================================\n")
